name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.15.0'

    - name: Install dependencies
      run: |
        npm install
        echo "Dependencies installed."

    - name: Run tests
      run: |
        npm test
        echo "Tests completed."

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    if: success() 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.15.0'

    - name: Install dependencies
      run: |
        npm install
        echo "Dependencies installed."

    - name: Build application
      run: |
        npm run build
        echo "Build completed."

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build
    if: success() 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        # Copy files to EC2 instance
        scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@16.171.146.74:~/ci_cd

        # Connect to EC2 and deploy
        ssh -o StrictHostKeyChecking=no ubuntu@16.171.146.74 << 'EOF'
          # Navigate to the deployment directory
          cd ~/ci_cd

          # Install dependencies
          npm install --production

          # Start the application
          npm start

          # Check for errors and log output
          if [ $? -ne 0 ]; then
            echo "Deployment failed!"
            exit 1
          else
            echo "Deployment successful!"
          fi
        EOF
